name: Lint
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
jobs:
  run_tests:
    name: Ensure black is happy with formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run unit tests
        run: python3 -m black .
